add docu, restructure workflow

diff --git a/.github/workflows/reusable-release-workflow.yaml b/.github/workflows/reusable-release-workflow.yaml
--- a/.github/workflows/reusable-release-workflow.yaml
+++ b/.github/workflows/reusable-release-workflow.yaml
@@ -13,9 +13,9 @@ on:
         default: true
         required: true
       artifact:
-        description: Add artifacts to the release. All files from /docs are added to the release.
-        type: boolean
-        default: true
+        description: Add artifacts to the release. All files from the provided folder(s) are added to the release. Folders or files are seperated by a single whitespace (e.g. file.txt folder/). **Do not use docs/**.
+        type: string
+        default: ''
         required: false
       force:
         description: "If force is true, already published releases can be overwritten. Caution: This action deletes already published releases and can **not** be undone!"
@@ -27,24 +27,91 @@ on:
 
 
 jobs:
+  variables: 
+    runs-on: ubuntu-latest
+    outputs:
+      REPO_NAME: ${{ steps.var.outputs.REPO_NAME }}
+      VERSION: ${{ steps.var.outputs.VERSION }}
+      BASE_BRANCH: ${{ steps.var.outputs.BASE_BRANCH }}  # branch to release, only main supported
+      RELEASE_NAME: ${{ steps.var.outputs.RELEASE_NAME }}
+      RELEASE_TAG: ${{ steps.var.outputs.RELEASE_TAG }}
+      RELEASE_BRANCH_NAME: ${{ steps.var.outputs.RELEASE_BRANCH_NAME }}
+      RELEASE_NOTES: ${{ steps.var.outputs.RELEASE_NOTES }}
+      RELEASE_ASSETS_NAME: ${{ steps.var.outputs.RELEASE_ASSETS_NAME }}
+      DOC_PATH: ${{ steps.var.outputs.DOC_PATH }}
+      DOC_ARTIFACT_NAME: ${{ steps.var.outputs.DOC_ARTIFACT_NAME }}
+
+    steps:
+    - name: Validate input parameters
+      id: param_check
+      run: |
+        VERSION_REGEX="^v[0-9]+\.[0-9]+\.[0-9]+$"
+        version=${{ github.event.inputs.version }}
+        if [[ ! "$version" =~ $VERSION_REGEX ]]; then
+          echo "Invalid version format: $version . Please provide a version matching the pattern 'v[number].[number].[number]'."
+          exit 1
+        fi
+
+    - name: Extract variables for Release action  # Adjust names only here
+      id: var
+      run: |
+        version=$(echo ${{ github.event.inputs.version }} | grep -oP '[0-9]+\.[0-9]+\.[0-9]+')  # alternative: '[[:digit:]]+\.[[:digit:]]+\.[[:digit:]]'
+        repo_name=$( echo ${{ github.repository }} | sed -E "s/^.*\///" )
+        echo "REPO_NAME=$repo_name" >> $GITHUB_OUTPUT
+        echo "VERSION"=$version >> $GITHUB_OUTPUT
+        echo "BASE_BRANCH=main" >> $GITHUB_OUTPUT
+        echo "RELEASE_NAME=\"$repo_name Release $version\"" >> $GITHUB_OUTPUT
+        echo "RELEASE_TAG=v$version" >> $GITHUB_OUTPUT
+        echo "RELEASE_BRANCH_NAME=release/$version" >> $GITHUB_OUTPUT
+        echo "RELEASE_NOTES=RELEASE.md" >> $GITHUB_OUTPUT
+        echo "RELEASE_ASSETS_NAME=artifact" >> $GITHUB_OUTPUT
+        echo "DOC_PATH=docs/" >> $GITHUB_OUTPUT
+        echo "DOC_ARTIFACT_NAME=$repo_name-api-sepc-docu-v$version" >> $GITHUB_OUTPUT
+
+
+  api-docu:
+    runs-on: ubuntu-latest
+    needs: variables
+
+    steps:
+      - uses: actions/checkout@v4
+      - uses: actions/setup-node@v4
+        with:
+          node-version: latest
+      - name: create API documentation
+        run: |
+          mkdir -p ${{ needs.variables.outputs.DOC_PATH }}
+          for file in $(ls *.yaml | sed 's/\.yaml$//'); do
+            doc_file=$file-${{ needs.variables.outputs.VERSION }}-doc-${{ github.sha }}.html
+            npx --silent @redocly/cli@1.8.2 build-docs --output ${{ needs.variables.outputs.DOC_PATH }}$doc_file $file.yaml
+            echo "Created documentation: $doc_file"
+          done;
+      - uses: actions/upload-artifact@v4
+        id: upload_artifact
+        with:
+          name: ${{ needs.variables.outputs.DOC_ARTIFACT_NAME }}
+          path: ${{ needs.variables.outputs.DOC_PATH }}
+          retention-days: 1
+          if-no-files-found: error
+          overwrite: true
+
+      - name: Upload docu artifacts
+        run: |
+          echo 'Uploaded artifacts with ID ${{ steps.upload_artifact.outputs.artifact-id }}.'
+ 
+
   release:
     runs-on: ubuntu-latest
+    needs: variables
 
     permissions:
       contents: write
       pull-requests: write
 
-    steps:
-      - name: Validate input parameters
-        id: param_check
-        run: |
-          VERSION_REGEX="^v[0-9]+\.[0-9]+\.[0-9]+$"
-          version=${{ github.event.inputs.version }}
-          if [[ ! "$version" =~ $VERSION_REGEX ]]; then
-            echo "Invalid version format: $version . Please provide a version matching the pattern 'v[number].[number].[number]'."
-            exit 1
-          fi
+    outputs:
+      RELEASE_ID: ${{ steps.create_release_draft.outputs.RELEASE_ID }}
 
+    steps:
       - name: Checkout repository
         uses: actions/checkout@v4
 
@@ -54,27 +121,14 @@ jobs:
           repository: ${{github.repository}}.wiki
           path: wiki
 
-      - name: Extract variables for Release  # Adjust names only here
-        id: var
-        run: |
-          version=$(echo ${{ github.event.inputs.version }} | grep -oE '[0-9]+\.[0-9]+\.[0-9]+')  # alternative: '[[:digit:]]+\.[[:digit:]]+\.[[:digit:]]'
-          repo_name=$( echo ${{ github.repository }} | sed -E "s/^.*\///" )
-          echo "VERSION"=$version >> $GITHUB_OUTPUT
-          echo "RELEASE_NAME=$repo_name Release $version" >> $GITHUB_OUTPUT
-          echo "RELEASE_TAG=v$version" >> $GITHUB_OUTPUT
-          echo "RELEASE_BRANCH=main" >> $GITHUB_OUTPUT
-          echo "RELEASE_NOTES=RELEASE.md" >> $GITHUB_OUTPUT
-          echo "RELEASE_ASSETS_FOLDER=docs/" >> $GITHUB_OUTPUT
-          echo "RELEASE_ASSETS_NAME=artifact" >> $GITHUB_OUTPUT
-
       - name: Get release note content from wiki
         id: release_note_body
         run: |
-          regex="### Release ${{ steps.var.outputs.RELEASE_TAG }}[[:print:]]*[[:cntrl:]]{2}([^-][[:print:]]*[[:cntrl:]]{1,2})*(- [[:print:]]*[[:cntrl:]])+[[:cntrl:]]{2}"  ## matches section + optional text + at least one bullet point
+          regex="### Release ${{ needs.variables.outputs.RELEASE_TAG }}[[:print:]]*[[:cntrl:]]{2}([^-][[:print:]]*[[:cntrl:]]{1,2})*(- [[:print:]]*[[:cntrl:]])+[[:cntrl:]]{2}"  ## matches section + optional text + at least one bullet point
           content=$(grep -ozE "$regex" wiki/Roadmap.md | tr "\0" "\n" | tail -n +3)
           # abort if content is empty --> wiki page must be present before release
           if [ -z "$content" ]; then
-            echo "Found no data for ${{ steps.var.outputs.RELEASE_NAME }} at wiki/Roadmap (${{ github.repository }}). Please create a section <<Release ${{ steps.var.outputs.RELEASE_TAG }}>> and fill in details for the release by following the instructions at the .github Wiki. A template can be found at https://github.com/swissfintechinnovations/.github/wiki/Release-Roadmap-Example."
+            echo "Found no data for ${{ needs.variables.outputs.RELEASE_NAME }} at wiki/Roadmap (${{ github.repository }}). Please create a section <<Release ${{ needs.variables.outputs.RELEASE_TAG }}>> and fill in details for the release by following the instructions at the .github Wiki. A template can be found at https://github.com/swissfintechinnovations/.github/wiki/Release-Roadmap-Example."
             exit 1
           fi
           body="$content"$'\n\n# \n\n'
@@ -83,10 +137,10 @@ jobs:
       - name: Check file version
         id: check_version
         run: |
-          BASE_BRANCH="${{ steps.var.outputs.RELEASE_BRANCH }}"
+          BASE_BRANCH=${{ needs.variables.outputs.BASE_BRANCH }}
 
           git checkout -q origin/$BASE_BRANCH
-          release_version=${{ steps.var.outputs.VERSION }}
+          release_version=${{ needs.variables.outputs.VERSION }}
           versions=$(grep -Eo 'version: [0-9]+\.[0-9]+\.[0-9]+' *.yaml | grep -Eo '[0-9]+\.[0-9]+\.[0-9]+')
           versions_outdated='false'
           for version in $versions; do
@@ -101,29 +155,26 @@ jobs:
         id: create_release_branch
         if: steps.check_version.outputs.VERSIONS_OUTDATED == 'true'
         run: |
-          BASE_BRANCH="${{ steps.var.outputs.RELEASE_BRANCH }}"
-          BRANCH_NAME="release/${{ steps.var.outputs.VERSION }}"
+          RELEASE_BRANCH_NAME=${{ needs.variables.outputs.RELEASE_BRANCH_NAME }}
 
           git config --global user.name "sfti bot"
           git config --global user.email "github-bot@common-api.ch"
 
-          git checkout -q origin/$BASE_BRANCH
-          git checkout $BRANCH_NAME 2>/dev/null || git checkout -b $BRANCH_NAME  # checkout branch or create new one if not exists
-
-          echo "BRANCH_NAME=$BRANCH_NAME" >> $GITHUB_OUTPUT
+          git checkout $RELEASE_BRANCH_NAME 2>/dev/null || git checkout -b $RELEASE_BRANCH_NAME  # checkout branch or create new one if not exists
 
       - name: Update version in files
         id: update_version
         if: steps.check_version.outputs.VERSIONS_OUTDATED == 'true'
         run: |
-          VERSION="${{ steps.var.outputs.VERSION }}"
-          RELEASE_NAME="${{ steps.var.outputs.RELEASE_NAME }}"
-          BRANCH_NAME="${{ steps.create_release_branch.outputs.BRANCH_NAME }}"
+          VERSION=${{ needs.variables.outputs.VERSION }}
+          RELEASE_NAME=${{ needs.variables.outputs.RELEASE_NAME }}
+          BASE_BRANCH=${{ needs.variables.outputs.BASE_BRANCH }}
+          RELEASE_BRANCH_NAME=${{ needs.variables.outputs.RELEASE_BRANCH_NAME }}
 
           echo "Prepare Release $RELEASE_NAME: update version number in yaml files"
-          git checkout -q $BRANCH_NAME
+          git checkout -q $RELEASE_BRANCH_NAME
           git fetch -q origin
-          git reset --hard origin/main
+          git reset --hard origin/$BASE_BRANCH
 
           sed -E -i "s/version: [0-9]+\.[0-9]+\.[0-9]+/version: $VERSION/" *.yaml
 
@@ -131,22 +182,22 @@ jobs:
           # commit only if there was changes in the yaml files
           git diff --staged --quiet || git commit -m "Automated version update"
           # git commit --quiet --allow-empty -m '[skip-workflow]'
-          git push --quiet --set-upstream origin $BRANCH_NAME
+          git push --quiet --set-upstream origin $RELEASE_BRANCH_NAME
 
       - name: "Rollback: Delete Branch"
         if: failure() && steps.update_version.outcome == 'failure'
         run: |
-          git checkout -q main
-          git branch -D ${{ steps.create_release_branch.outputs.BRANCH_NAME }}
-          git push origin --delete ${{ steps.create_release_branch.outputs.BRANCH_NAME }}
+          git checkout -q ${{ needs.variables.outputs.BASE_BRANCH }}
+          git branch -D ${{ needs.variables.outputs.RELEASE_BRANCH_NAME }}
+          git push origin --delete ${{ needs.variables.outputs.RELEASE_BRANCH_NAME }}
 
       - name: Create and merge Pull Request
         id: create_pr
         if: steps.check_version.outputs.VERSIONS_OUTDATED == 'true'
         run: |
-          BASE_BRANCH=${{ steps.var.outputs.RELEASE_BRANCH }}
+          BASE_BRANCH=${{ needs.variables.outputs.BASE_BRANCH }}
 
-          response=$(gh pr create -B $BASE_BRANCH -H ${{ steps.create_release_branch.outputs.BRANCH_NAME }} --title 'Automated version update to version ${{ steps.var.outputs.VERSION }}' --body 'Created by Github action (release workflow)')
+          response=$(gh pr create -B $BASE_BRANCH -H ${{ needs.variables.outputs.RELEASE_BRANCH_NAME }} --title 'Automated version update to version ${{ needs.variables.outputs.VERSION }}' --body 'Created by Github action (release workflow)')
           number=$(echo "$response" | grep -oE '[0-9]+$')  # parse GitHub PR link to extract PR number
           echo "PR_NUMBER=$number" >> $GITHUB_OUTPUT
 
@@ -170,8 +221,8 @@ jobs:
         run: |
           ACCESS_TOKEN=${{ secrets.GITHUB_TOKEN }}
           REPO_NAME=${{ github.repository }}
-          TAG=${{ steps.var.outputs.RELEASE_TAG }}
-          RELEASE_NAME="${{ steps.var.outputs.RELEASE_NAME }}"
+          TAG=${{ needs.variables.outputs.RELEASE_TAG }}
+          RELEASE_NAME=${{ needs.variables.outputs.RELEASE_NAME }}
 
           # Get the release ID belonging to the release tag
           RELEASE_ID=$(curl -sS -X GET -H "Authorization: Bearer $ACCESS_TOKEN" "https://api.github.com/repos/$REPO_NAME/releases" | jq -r ".[] | select(.name == \"$RELEASE_NAME\") | .id")
@@ -216,10 +267,9 @@ jobs:
             -H "Accept: application/vnd.github.v3+json" \
             "https://api.github.com/repos/$REPO_NAME/releases" \
             -d '{
-              "tag_name": "'"${{ steps.var.outputs.RELEASE_TAG }}"'",
-              "target_commitish": "'"${{ steps.var.outputs.RELEASE_BRANCH }}"'",
-              "name": "'"${{ steps.var.outputs.RELEASE_NAME }}"'",
-              "name": "'"${{ steps.var.outputs.RELEASE_NAME }}"'",
+              "tag_name": "'"${{ needs.variables.outputs.RELEASE_TAG }}"'",
+              "target_commitish": "'"${{ needs.variables.outputs.BASE_BRANCH }}"'",
+              "name": "'${{ needs.variables.outputs.RELEASE_NAME }}'",
               "body": "'"${{ steps.release_note_body.outputs.BODY }}"'",
               "generate_release_notes": true,
               "draft": true
@@ -234,27 +284,41 @@ jobs:
 
           echo "RELEASE_ID=$(echo $RESPONSE | grep -o -z '\{.*\}' | jq -r '.id')" >> $GITHUB_OUTPUT
 
+
+  artifact:
+    runs-on: ubuntu-latest
+    needs:
+      - variables
+      - api-docu
+      - release
+
+    steps:
+      - uses: actions/checkout@v4
+
+      - name: Download documentation
+        uses: actions/download-artifact@v4
+        with:
+          name: ${{ needs.variables.outputs.DOC_ARTIFACT_NAME }}
+          path: ${{ needs.variables.outputs.DOC_PATH }}
+
       - name: Upload artifacts
         id: upload_artifact
-        # ensure assert folder exsits and not empty otherwise skip step
-        if: github.event.inputs.artifact == 'true' && (hashFiles(steps.var.outputs.RELEASE_ASSETS_FOLDER) != '')
         run: |
           ACCESS_TOKEN=${{ secrets.GITHUB_TOKEN }}
           REPO_NAME=${{ github.repository }}
-          RELEASE_ID=${{ steps.create_release_draft.outputs.RELEASE_ID }}
-          RELEASE_ASSETS_FOLDER=${{ steps.var.outputs.RELEASE_ASSETS_FOLDER }}
-          RELEASE_ASSETS_NAME=${{ steps.var.outputs.RELEASE_ASSETS_NAME }}
+          RELEASE_ID=${{ needs.release.outputs.RELEASE_ID }}
+          RELEASE_ASSETS_NAME=${{ needs.variables.outputs.RELEASE_ASSETS_NAME }}
 
           RELEASE_ASSETS_ZIP=$RELEASE_ASSETS_NAME.zip
           RELEASE_ASSETS_TARGZ=$RELEASE_ASSETS_NAME.tar.gz
 
-          zip -qr $RELEASE_ASSETS_ZIP $RELEASE_ASSETS_FOLDER
+          zip -qr --must-match $RELEASE_ASSETS_ZIP ${{ needs.variables.outputs.DOC_PATH }} ${{ github.event.inputs.artifact}}
 
           RESPONSE=$(curl -sS -i -X POST \
             -H "Authorization: Bearer $ACCESS_TOKEN" \
             -H "Content-Type: application/octet-stream" \
-            "https://uploads.github.com/repos/$REPO_NAME/releases/$RELEASE_ID/assets?name=$RELEASE_ASSETS_ZIP" \
-            --data-binary "@$RELEASE_ASSETS_ZIP" )
+            --data-binary "@$RELEASE_ASSETS_ZIP" \
+            https://uploads.github.com/repos/$REPO_NAME/releases/$RELEASE_ID/assets?name=$RELEASE_ASSETS_ZIP)
 
           if [[ $(echo $RESPONSE | head -n 1 | cut -d$' ' -f2 ) -ne 201 ]]; then
             echo "Failed to upload release asset $RELEASE_ASSETS_ZIP. Received response from GitHub API:"
@@ -263,11 +327,13 @@ jobs:
             exit 1
           fi
 
-          tar -czf $RELEASE_ASSETS_TARGZ $RELEASE_ASSETS_FOLDER
+          tar -czf $RELEASE_ASSETS_TARGZ ${{ needs.variables.outputs.DOC_PATH }} ${{ github.event.inputs.artifact}}
 
-          RESPONSE=$(curl -sS -i -X POST -H "Authorization: Bearer $ACCESS_TOKEN" -H "Content-Type: application/octet-stream" \
-          --data-binary "@$RELEASE_ASSETS_TARGZ" \
-          "https://uploads.github.com/repos/$REPO_NAME/releases/$RELEASE_ID/assets?name=$RELEASE_ASSETS_TARGZ")
+          RESPONSE=$(curl -sS -i -X POST \
+            -H "Authorization: Bearer $ACCESS_TOKEN" \
+            -H "Content-Type: application/octet-stream" \
+            --data-binary "@$RELEASE_ASSETS_TARGZ" \
+            https://uploads.github.com/repos/$REPO_NAME/releases/$RELEASE_ID/assets?name=$RELEASE_ASSETS_TARGZ)
 
           if [[ $(echo $RESPONSE | head -n 1 | cut -d$' ' -f2 ) -ne 201 ]]; then
             echo "Failed to upload release asset $RELEASE_ASSETS_TARGZ. Received response from GitHub API:"
@@ -276,13 +342,41 @@ jobs:
             exit 1
           fi
 
+
+  rollback:
+    runs-on: ubuntu-latest
+    needs: 
+      - release
+      - api-docu
+      - artifact
+    if: |
+      always() &&
+      (needs.api-docu.result == 'failure' && needs.release.result == 'success' ||
+      needs.artifact.result == 'failure' && needs.release.result == 'success')
+    steps:
+      - name: Rollback on error, delete release
+        run: |
+          ACCESS_TOKEN=${{ secrets.GITHUB_TOKEN }}
+          REPO_NAME=${{ github.repository }}
+          RELEASE_ID=${{ needs.release.outputs.RELEASE_ID }}
+          curl -sS -X DELETE -H "Authorization: Bearer $ACCESS_TOKEN" "https://api.github.com/repos/$REPO_NAME/releases/$RELEASE_ID"
+
+
+  publish:
+    runs-on: ubuntu-latest
+    needs:
+      - variables
+      - release
+      - artifact
+    if: github.event.inputs.draft == 'false'
+
+    steps:
       - name: Publish release
-        if: github.event.inputs.draft == 'false'
         id: publish_release
         run: |
           ACCESS_TOKEN=${{ secrets.GITHUB_TOKEN }}
           REPO_NAME=${{ github.repository }}
-          RELEASE_ID=${{ steps.create_release_draft.outputs.RELEASE_ID }}
+          RELEASE_ID=${{ needs.release.outputs.RELEASE_ID }}
 
           RESPONSE=$(curl -sS -i -X PATCH \
             -H "Authorization: Bearer $ACCESS_TOKEN" \
